### ISSUE TITLE
Implement more fields to be updated from /api/v1/games/{id}

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#195] opened 2023-09-14 20:09 UTC
**Is your feature request related to a problem? Please describe.**
The majority of fields related to a game in the database should be overwritable by the admin, be it through the UI or purely through API calls as an advanced feature.

**Describe the solution you'd like**

When a rawg field is updated by the user, there should be a flag which ignores that field when a cache update takes place. For instance, if the description is updated by the user, it should not be overwritten by a cache update while the website_url, rawg_title and metacritic_rating should continue to be updated.

The following fields should be updatable:
* entity_version
* rawg_id
* title
* version
* release_date
* description
* box_image
* background_image
* website_url
* metacritic_rating
* average_playtime
* early_access
* type
* progresses
* publishers
* developers
* stores
* tags
* genres

**Comment by Alfagun74** [comment] 2023-09-18 05:48
Duplicate of #161

**Closed by Alfagun74** 2023-09-18 05:48 UTC
Labels: 🔧 feature, 🎛️ server
