### ISSUE TITLE
Add ability to add files to games (updates etc)

### ISSUE THREAD

**Issue by ozhound** [Phalcode/gamevault-backend#179] opened 2023-08-26 11:46 UTC
**Is your feature request related to a problem? Please describe.**
Updates are always happening for games, i want to provide a facility to download an update to the game so the user doesnt have to download the entire file again.

**Describe the solution you'd like**
On the game page, have a list of "Additional, Optional Files"

**Describe alternatives you've considered**
Delete the original archive and replace with one with the latest version, or the original with the update included, but this means that someone would have to download the file again when the update could be tiny compare to the main file

**Comment by Alfagun74** [comment] 2023-08-26 12:34
Duplicate of https://github.com/Phalcode/gamevault-backend/issues/149, Sorry ✌️

**Closed by Alfagun74** 2023-08-26 12:34 UTC
Labels: 🔧 feature, 🎛️ server
