### ISSUE TITLE
RAWG integration cannot find properly

### ISSUE THREAD

**Issue by nodiaque** [Phalcode/gamevault-backend#257] opened 2024-03-11 20:27 UTC
Hello,

I've installed the back-end on unraid with the database and enabled all store. I add the game with the exact name from RAWG, let's say Hellbound. When I get into the client, I see it has downloaded first image from somewhere on the internet and later, it has a RAWG refresh. The name change for something else it and sync with anything.

I added 40 games and it did that for all 40 games. I normally have the right images (sometime not) but the RAWG sync always sync with something else.

**Comment by Alfagun74** [comment] 2024-03-11 21:48
Is only the image wrong or all data?

Can you show me your .env file or configuration?

Are you aware of [this](https://gamevau.lt/docs/client-docs/how-to-use#modifying-games)?

Thanks in advance.

**Comment by nodiaque** [comment] 2024-03-11 22:02
Getting back with hebfike as soon as I get back home. As for the manual editing, yes I'm aware, that's why I said I have to manually modify all of them one by one.

**Comment by nodiaque** [comment] 2024-03-12 02:08
ok for the env file, I have the default one cause there's nothing in my gamevault folder except my image cache. I do have /data mounted but nothing in it. Weird?

I have environment variable from unraid template
RAWG_API_INCLUDED_STORES: = 0

I just tried a new game, Infinity Wars

Here's the result, notice how RAWG tagger to anything
![image](https://github.com/Phalcode/gamevault-backend/assets/324425/aff2954f-f23e-4b05-ac4d-b1cc702e4d6b)


Here's the file
![image](https://github.com/Phalcode/gamevault-backend/assets/324425/6b66dc81-d661-44c3-ac06-781f76186c87)

RAWG
https://rawg.io/games/infinity-wars
![image](https://github.com/Phalcode/gamevault-backend/assets/324425/500b6518-4605-4d3c-bacc-fa8dfab8e0c8)


And another game, HeroQuest II: Legacy of Sorasil
![image](https://github.com/Phalcode/gamevault-backend/assets/324425/a4c60a3f-4595-4ac0-9fc9-d0625a5357be)

![image](https://github.com/Phalcode/gamevault-backend/assets/324425/100e8e69-0ced-44dd-ab29-f2469cf60032)

https://rawg.io/games/heroquest-ii-legacy-of-sorasil

**Comment by nodiaque** [comment] 2024-03-12 11:18
Hello, it was on the default before and it was worst because lots of game would simply not be found even with manual search. Games like Heroes of Might and Magic 4 Winds of War for exemple.

I don't know how the search is done, but right now, what it find is very different from the search. Just HeroQuest 2, the only matching word is "2" and "of". In the manual search, when I input exactly the title, it's the first return.

**Comment by Alfagun74** [comment] 2024-03-12 12:05
This is horrible, yes. 

Can set the log level to debug, index about 5-10 new games and send a full log file so i can analyze?

**Comment by nodiaque** [comment] 2024-03-12 12:13
Ok, I've done it. Where can I find the file on the docker? Cause there's nothing in /data, I'm wondering why this is mapped...

**Comment by nodiaque** [comment] 2024-03-12 12:39
Here's the log, and I'm amazed at how it find nothing!

Check for the following game:
Police Quest Collection ==> Matched as Falcon Collection
Risk 2 ==> Matched as Grand Turismo 2
Prototype => Matched as Prototype! (A first!)
Zombie In My Pocket New ==> There's A Zombie in my Closet (and image is Zombie Ate My neighboor)
Space Quest 2 Vohaul's Revenge ==> King's Quest1+2+3

Weird thing is looking at the log file, none have the actual game in the game list it find so something is very wrong. Unless the search doesn't use the "all store" like the main search?
[gamevault-backend-2024-03-12.log](https://github.com/Phalcode/gamevault-backend/files/14572249/gamevault-backend-2024-03-12.log)

**Comment by Alfagun74** [comment] 2024-03-13 06:56
Let me analyze this thoroughly and come back to you asap.

**Comment by Alfagun74** [comment] 2024-03-13 07:11
I just checked the logs and the acurracy is truly horrible! Almost looks like it takes page 4 or something. Never seen this behaviour before. Let me try to reproduce it. May i ask what country you are located in?

**Comment by Alfagun74** [comment] 2024-03-13 09:07
I can not reproduce this unfortunately. Note the Config in the Logs. Stores=0.

(I changed the logs so they look a bit better, but the application logic is the same)

[gamevault-backend-2024-03-13.log.json](https://github.com/Phalcode/gamevault-backend/files/14585096/gamevault-backend-2024-03-13.log.json)

Can you try and check if the `unstable` v10.2.1 Pre-Release image behaves any different for you?

**Comment by nodiaque** [comment] 2024-03-13 11:15
> I just checked the logs and the acurracy is truly horrible! Almost looks like it takes page 4 or something. Never seen this behaviour before. Let me try to reproduce it. May i ask what country you are located in?

I'm in Canada.

Could it be that the env in the docker doesn't say to search for all store? Because looking at my log, the proper game isn't even in the list.

**Comment by Alfagun74** [comment] 2024-03-13 11:27
No i just checked. It says `"INCLUDED_STORES":[0]` in your log aswell.

I will VPN to canada and rerun the experiment to see if RAWG behaves any different overseas. This is really bugging me.

**Comment by Alfagun74** [comment] 2024-03-13 11:55
Canada Experiment Results:
[gamevault-backend-maple-sirup-edition-2024-03-13.log.json](https://github.com/Phalcode/gamevault-backend/files/14587135/gamevault-backend-maple-sirup-edition-2024-03-13.log.json)

**Comment by nodiaque** [comment] 2024-03-13 12:09
could it be because of my folder? The way I structure my stuff is I have a share with all my games. Each games have a folder where I put the supported file in it. Looking at my log, I see a lot of "ignoring unsuported extension" and this is for all of the folder it log that

**Comment by Alfagun74** [comment] 2024-03-13 12:16
I replicated your folder structure in my tests aswell so i dont see a reason for this.
It's nothing unfamiliar i haven't yet seen either. The "ignoring unsuported extension" is just an informational log, and you can ignore it.

Yes the tag is gamevault-backend:unstable

**Comment by nodiaque** [comment] 2024-03-13 12:20
samething with unstable :(

**Comment by Alfagun74** [comment] 2024-03-13 12:54
Let me ask in our discord community if anyone experiences something similar.

**Comment by nodiaque** [comment] 2024-03-13 13:29
In case, here's my docker-compose
![image](https://github.com/Phalcode/gamevault-backend/assets/324425/bf814c1d-c040-4621-b8c7-55d92f552ea1)

**Comment by Alfagun74** [comment] 2024-03-13 13:34
Can you Pull unstable again and gram me a fresh log again? I made them a bit more verbose.

**Comment by nodiaque** [comment] 2024-03-13 16:07
Getting lot's of error and take 5 minutes to start with that version. Still haven't scanner the files yet

**Comment by Alfagun74** [comment] 2024-03-13 20:05
Apologies, my mistake. It seems I introduced a bug while under stress. I'll release a new unstable version that should be fixed shortly.

**Comment by Alfagun74** [comment] 2024-03-20 17:59
@nodiaque could you try to pull a log with the latest unstable version?

**Comment by Alfagun74** [comment] 2024-03-29 09:16
@nodiaque Hi, have you had any time to test this out maybe?

**Comment by nodiaque** [comment] 2024-03-30 00:56
sorry I was away for a while. Just updated and remove the game, restart the container and no dice :(

I even have weirder things now like image that have nothing to do with anything
![image](https://github.com/Phalcode/gamevault-backend/assets/324425/267a2a3f-9dfe-4e9d-a82b-2929a0d3987a)

![image](https://github.com/Phalcode/gamevault-backend/assets/324425/024e4641-5686-4104-bc29-b776e7eeb9f9)


[gamevault-backend-2024-03-29.log](https://github.com/Phalcode/gamevault-backend/files/14809480/gamevault-backend-2024-03-29.log)

**Comment by Alfagun74** [comment] 2024-03-31 00:05
oh man, at this point i don't understand it either. You may need to wait for https://github.com/Phalcode/gamevault-backend/issues/258 to use this app properly

**Comment by Alfagun74** [comment] 2024-03-31 23:15
Does the same issue happen when you only have a /files volume with one single game zip in it?

**Comment by nodiaque** [comment] 2024-03-31 23:23
Yes, risk 2 is a single zip file and have this problem.

**Comment by Alfagun74** [comment] 2024-04-01 00:49
i meant the volume should be empty with just that single file in it

**Comment by nodiaque** [comment] 2024-04-01 01:00
Volume or folder? Risk 2 is alone in it's folder

![image](https://github.com/Phalcode/gamevault-backend/assets/324425/12cd985a-d3dc-4f7b-9102-c3a60a03aaa0)

**Comment by Alfagun74** [comment] 2024-04-01 02:07
I want to see if it works if the entire volume mapped to /files only contains a single game zip file.

**Comment by Alfagun74** [comment] 2024-04-03 05:20
We'll prioritize working on task #258 with high importance. I appreciate your patience while we tackle it.

**Comment by nodiaque** [comment] 2024-04-04 20:54
just tried with only risk 2 in a new installation. Same result, risk 2 was matched as gran turismo 2
![image](https://github.com/Phalcode/gamevault-backend/assets/324425/fd3b5e01-3654-4446-b1a5-16afd734da9e)

**Comment by Alfagun74** [comment] 2024-04-04 21:01
![image](https://github.com/Phalcode/gamevault-backend/assets/22225051/8f299967-43d4-4a62-bc28-c7bd3b2c343e)
Im out of ideas, Sorry. Noone in the community has experienced this yet either, so i really am clueless or missing a key detail.

Oh wait!

I have one final idea. Could you hit me up on our [discord](https://discord.com/invite/NEdNen2dSu) so i can send you my own rawg key in private to see if it is an issue with your API Key? Maybe Rawg just treats it different.

**Comment by Alfagun74** [comment] 2024-04-14 00:02
Well, folks, after what feels like a coding odyssey spanning weeks and more late nights than I care to count, we've finally cracked the case! And what was the culprit, you ask? Drumroll, please... **TIMEZONES?!** Yes, you heard that right.

It turns out that our dear friend @nodiaque's UNRAID server possesses some mystical powers, particularly when it comes to time zones. Picture this: every container it runs defaults to "America/New York". Now, ordinarily, that shouldn't be a problem, right? We're saving our dates in the database as UTC, after all. 

But hold on to your hats, because here's where it gets wild. Enter node-postgres, a seemingly innocent connection layer between Postgres and JavaScript. Innocent, that is, until you realize that it has a rather mischievous habit of converting timestamps to the local timezone before saving them into the database. *Facepalm*

References:
- [Node-Postgres Issue #2141](https://github.com/brianc/node-postgres/issues/2141)
- [TypeORM Issue #4519](https://github.com/typeorm/typeorm/issues/4519)
- [Node-Postgres Issue #1746](https://github.com/brianc/node-postgres/issues/1746)
- [TypeORM Issue #2390](https://github.com/typeorm/typeorm/issues/2390)
- [TypeORM Issue #2622](https://github.com/typeorm/typeorm/issues/2622)

Fixed in v11.0.3

**Closed by Alfagun74** 2024-04-14 00:02 UTC
Labels: 🪲 bug, 🎛️ server
