### ISSUE TITLE
FR: Expand list of games for tall client window.

### ISSUE THREAD

**Issue by alexfornuto** [Phalcode/gamevault-backend#324] opened 2024-10-27 07:59 UTC
**Is your feature request related to a problem? Please describe.**
When the client window is taller than it is wide, the list of games does not expand to the bottom, wasting space on the screen:
![image](https://github.com/user-attachments/assets/a6d54e44-f2f8-45a1-8442-0b8063535919)

**Describe the solution you'd like**
I'd like the list of games to expand in this window form.

**Describe alternatives you've considered**
One could maximize the window to fit the screen, but that's not great for multi-taskers.

**Comment by Alfagun74** [comment] 2024-10-28 09:09
Wrong Repo and Duplicate of https://github.com/Phalcode/gamevault-app/issues/395

**Closed by Alfagun74** 2024-10-28 09:09 UTC
Labels: 🔧 feature, 🎛️ server
